/**
 *  Calendar Code
 * 
 * fullCheckoutsToCalender() & combineDateAndTime() - syncs calendar
 * tallyCalendarCheckouts() - tallys scheduled checkouts on the data page
 * deleteCheckoutsFromCalendar() - for clearing the calendar
 * 
 **/

function fullCheckoutsToCalendar() {
  const ss = SpreadsheetApp.getActive();
  const dataSheet = ss.getSheetByName('Data');
  const schedSheet = ss.getSheetByName('SCHEDULE HERE');
  
  if (!schedSheet || !dataSheet) {
    Logger.log('Error: "Data" or "SCHEDULE HERE" sheet not found.');
    return;
  }

  // --- 1. SETUP & SETTINGS ---
  const calendarId = dataSheet.getRange('O27').getValue().toString().trim();
  const buildingBase = dataSheet.getRange('O34').getValue().toString().trim();
  const calendar = CalendarApp.getCalendarById(calendarId);

  if (!calendar) {
    Logger.log('Error: Calendar ID in Data!O27 is invalid.');
    return;
  }

  // --- 2. MAP RA NAMES TO EMAILS ---
  const raEmailMap = {};
  for (let i = 1; i <= 13; i++) {
    const raSheet = ss.getSheetByName(`RA${i}`);
    if (!raSheet) continue;
    const name = raSheet.getRange('I3').getValue().toString().trim();
    const email = raSheet.getRange('I6').getValue().toString().trim(); 
    
    if (name && email) {
      // Force emails to lowercase for perfectly accurate comparisons later
      raEmailMap[name] = email.toLowerCase();
      raEmailMap[name.toLowerCase()] = email.toLowerCase(); 
    }
  }

  // --- 3. READ DATA & BUILD INTENDED SCHEDULE ---
  const schedLastRow = Math.max(schedSheet.getLastRow(), 46);
  const schedGrid = schedSheet.getRange(1, 1, schedLastRow, 24).getValues(); 
  const dataGrid = dataSheet.getRange(4, 3, 40, 11).getValues();

  // We will store all planned checkouts here before touching the calendar
  const plannedCheckouts = {};
  
  // Variables to figure out the exact date range of this week's schedule
  let searchStart = null;
  let searchEnd = null;

  for (let emailColIdx = 2; emailColIdx <= 22; emailColIdx += 2) {
    const dateVal = schedGrid[3][emailColIdx]; 
    const dataColIdx = (emailColIdx - 2) / 2;  

    if (!dateVal || isNaN(new Date(dateVal).getTime())) continue;

    // Track the earliest and latest dates for our calendar search
    const dTime = new Date(dateVal).getTime();
    if (!searchStart || dTime < searchStart.getTime()) searchStart = new Date(dTime);
    if (!searchEnd || dTime > searchEnd.getTime()) searchEnd = new Date(dTime);

    for (let rowIdx = 6; rowIdx < 46; rowIdx++) {
      const cellValue = schedGrid[rowIdx][emailColIdx].toString().trim();

      if (cellValue.includes('@')) {
        const residentEmail = cellValue.toLowerCase(); // Force lowercase
        const roomNumber = schedGrid[rowIdx][emailColIdx + 1]; 
        const timeStr = schedGrid[rowIdx][1]; 

        const startTime = combineDateAndTime(dateVal, timeStr);
        if (!startTime) continue;
        
        const endTime = new Date(startTime.getTime() + 15 * 60000); 

        const dataRowIdx = rowIdx - 6; 
        const raName = dataGrid[dataRowIdx][dataColIdx].toString().trim();
        const raEmail = raEmailMap[raName] || raEmailMap[raName.toLowerCase()];

        const eventTitle = `Checkout: ${buildingBase} ${roomNumber}`;
        const location = `${buildingBase} ${roomNumber}`;
        
        // Build the guest list array
        const guestsArray = [residentEmail];
        if (raEmail) guestsArray.push(raEmail); 

        // Create a unique identifier based on the exact start time and title/room
        const uniqueKey = `${startTime.getTime()}_${eventTitle}`;

        // Store it in our master list
        plannedCheckouts[uniqueKey] = {
          title: eventTitle,
          start: startTime,
          end: endTime,
          location: location,
          guestsStr: guestsArray.join(','), // String for creating the event
          guestsArray: guestsArray // Array for comparing emails
        };
      }
    }
  }

  // If no dates were found, stop here
  if (!searchStart || !searchEnd) {
    Logger.log('No valid dates found on the schedule.');
    return;
  }

  // Extend the end search time to the very end of that final day (11:59 PM)
  searchEnd.setHours(23, 59, 59, 999);

  // --- 4. SYNC WITH CALENDAR (DELETE OR IGNORE EXISTING) ---
  let eventsCreated = 0;
  let eventsDeleted = 0;

  // Pull all events currently on the calendar for this timeframe
  const existingEvents = calendar.getEvents(searchStart, searchEnd);

  for (let i = 0; i < existingEvents.length; i++) {
    const ev = existingEvents[i];
    const eTitle = ev.getTitle();
    
    // We only care about events generated by this script
    if (eTitle.indexOf('Checkout:') === 0) {
      const eStart = ev.getStartTime().getTime();
      const uniqueKey = `${eStart}_${eTitle}`;

      if (plannedCheckouts[uniqueKey]) {
        // MATCH FOUND FOR TIME & ROOM. Now, check if the emails are identical.
        
        // Sort both guest lists alphabetically so they compare perfectly regardless of order
        const plannedGuestsStr = plannedCheckouts[uniqueKey].guestsArray.slice().sort().join(',');
        
        // Get guests from calendar event, extract their emails, and filter out the calendar ID just in case it acts as a guest
        const calGuestsStr = ev.getGuestList()
          .map(g => g.getEmail().toLowerCase())
          .filter(email => email !== calendarId.toLowerCase()) 
          .sort()
          .join(',');

        if (plannedGuestsStr === calGuestsStr) {
          // Emails match perfectly! Remove it from our 'planned' list so we don't recreate it.
          delete plannedCheckouts[uniqueKey];
        } else {
          // Time and Room match, but EMAILS CHANGED. 
          // Format the ID correctly for the Advanced API by splitting off the @google.com
          const cleanEventId = ev.getId().split('@')[0];
          Calendar.Events.remove(calendarId, cleanEventId, {sendUpdates: "all"});
          eventsDeleted++;
        }

      } else {
        // It is on the calendar but NO LONGER on the sheet at all (or the time/room changed).
        // Format the ID correctly for the Advanced API
        const cleanEventId = ev.getId().split('@')[0];
        Calendar.Events.remove(calendarId, cleanEventId, {sendUpdates: "all"});
        eventsDeleted++;
      }
    }
  }

  // --- 5. CREATE NEW EVENTS ---
  // Any events left in our 'planned' list don't exist on the calendar (or had their emails changed).
  for (const key in plannedCheckouts) {
    const eventData = plannedCheckouts[key];
    try {
      calendar.createEvent(eventData.title, eventData.start, eventData.end, {
        location: eventData.location,
        guests: eventData.guestsStr,
        sendInvites: true 
      });
      eventsCreated++;
    } catch (e) {
      Logger.log(`Failed to create event for ${eventData.title}: ${e.message}`);
    }
  }

  Logger.log(`Sync Complete! Scheduled ${eventsCreated} new checkouts. Removed ${eventsDeleted} canceled/moved/updated checkouts.`);
  tallyCalendarCheckouts()
}

/**
 * Helper to merge a Date object and a Time string (e.g., "8:00 AM")
 */
function combineDateAndTime(dateObj, timeStr) {
  if (!timeStr) return null;
  const date = new Date(dateObj);
  const time = new Date(timeStr); 
  
  if (isNaN(time.getTime())) {
    const match = timeStr.match(/(\d+):(\d+)\s*(AM|PM)/i);
    if (!match) return null;
    let hours = parseInt(match[1]);
    const mins = parseInt(match[2]);
    const ampm = match[3].toUpperCase();
    if (ampm === "PM" && hours < 12) hours += 12;
    if (ampm === "AM" && hours === 12) hours = 0;
    date.setHours(hours, mins, 0, 0);
  } else {
    date.setHours(time.getHours(), time.getMinutes(), 0, 0);
  }
  return date;
}

function tallyCalendarCheckouts() {
  const ss = SpreadsheetApp.getActive();
  const dataSheet = ss.getSheetByName('Data');
  const schedSheet = ss.getSheetByName('SCHEDULE HERE');
  
  if (!schedSheet || !dataSheet) {
    Logger.log('Error: "Data" or "SCHEDULE HERE" sheet not found.');
    return;
  }

  // 1. SETUP CALENDAR
  const calendarId = dataSheet.getRange('O27').getValue().toString().trim();
  const calendar = CalendarApp.getCalendarById(calendarId);

  if (!calendar) {
    Logger.log('Error: Calendar ID in Data!O27 is invalid.');
    return;
  }

  // 2. MAP RA NAMES TO EMAILS (From RA1-RA13 sheets)
  const raEmailMap = {};
  const raCountsByEmail = {};
  
  for (let i = 1; i <= 13; i++) {
    const raSheet = ss.getSheetByName(`RA${i}`);
    if (!raSheet) continue;
    const name = raSheet.getRange('I3').getValue().toString().trim();
    const email = raSheet.getRange('I6').getValue().toString().trim().toLowerCase(); 
    
    if (name && email) {
      raEmailMap[name.toLowerCase()] = email;
      raCountsByEmail[email] = 0; // Initialize tracking count
    }
  }

  // 3. DETERMINE THE DATE RANGE FROM THE SCHEDULE GRID
  const schedLastRow = Math.max(schedSheet.getLastRow(), 46);
  const schedGrid = schedSheet.getRange(1, 1, schedLastRow, 24).getValues(); 
  
  let searchStart = null;
  let searchEnd = null;

  for (let emailColIdx = 2; emailColIdx <= 22; emailColIdx += 2) {
    const dateVal = schedGrid[3][emailColIdx]; 
    if (!dateVal || isNaN(new Date(dateVal).getTime())) continue;

    const dTime = new Date(dateVal).getTime();
    if (!searchStart || dTime < searchStart.getTime()) searchStart = new Date(dTime);
    if (!searchEnd || dTime > searchEnd.getTime()) searchEnd = new Date(dTime);
  }

  if (!searchStart || !searchEnd) {
    Logger.log('No valid dates found on the SCHEDULE HERE sheet.');
    return;
  }
  searchEnd.setHours(23, 59, 59, 999);

  // 4. FETCH CALENDAR EVENTS & PARSE INVITEES
  const existingEvents = calendar.getEvents(searchStart, searchEnd);

  existingEvents.forEach(ev => {
    const title = ev.getTitle();
    
    if (title.startsWith('Checkout:')) {
      const guestList = ev.getGuestList();
      
      guestList.forEach(guest => {
        const guestEmail = guest.getEmail().toLowerCase();
        
        // If the guest email belongs to an RA, count it
        if (raCountsByEmail.hasOwnProperty(guestEmail)) {
          raCountsByEmail[guestEmail]++;
        }
      });
    }
  });

  // 5. ALIGN COUNTS TO O7:O19 AND PRINT TO Q7:Q19
  const raNamesInO = dataSheet.getRange('O7:O19').getValues();
  const outputValues = [];

  // Loop through each row in your dashboard list
  for (let i = 0; i < raNamesInO.length; i++) {
    const name = raNamesInO[i][0].toString().trim().toLowerCase();
    const email = raEmailMap[name];
    
    if (name && email && raCountsByEmail[email] !== undefined) {
      // Name matches an active RA -> pull their live calendar total
      outputValues.push([raCountsByEmail[email]]);
    } else {
      // Cell is blank or name doesn't match an active RA profile -> write 0
      outputValues.push([0]);
    }
  }

  // Batch write all calculated counts directly to Column R
  dataSheet.getRange('Q7:Q19').setValues(outputValues);
  
  Logger.log('Success! Live checkout totals have been written to Data!Q7:Q19.');
}

function deleteCheckoutsFromCalendar() {
  const ss = SpreadsheetApp.getActive();
  const dataSheet = ss.getSheetByName('Data');
  const schedSheet = ss.getSheetByName('SCHEDULE HERE');
  
  if (!schedSheet || !dataSheet) {
    Logger.log('Error: "Data" or "SCHEDULE HERE" sheet not found.');
    return;
  }

  // --- 1. SETUP & CALENDAR ACCESS ---
  const calendarId = dataSheet.getRange('O27').getValue().toString().trim();
  const calendar = CalendarApp.getCalendarById(calendarId);

  if (!calendar) {
    Logger.log('Error: Calendar ID in Data!O27 is invalid.');
    return;
  }

  // --- 2. DETERMINE DATE RANGE FROM ROW 4 ---
  const lastCol = schedSheet.getLastColumn();
  // Read the entire 4th row
  const dateRowValues = schedSheet.getRange(4, 1, 1, lastCol).getValues()[0];
  let validDates = [];

  for (let i = 0; i < dateRowValues.length; i++) {
    let d = new Date(dateRowValues[i]);
    if (!isNaN(d.getTime())) {
      validDates.push(d);
    }
  }

  if (validDates.length === 0) {
    Logger.log('No valid dates found in Row 4 of SCHEDULE HERE. Cannot determine range.');
    return;
  }

  // Find the earliest and latest dates to define the search window
  validDates.sort((a, b) => a - b);
  const searchStart = new Date(validDates[0]);
  searchStart.setHours(0, 0, 0, 0);
  
  const searchEnd = new Date(validDates[validDates.length - 1]);
  searchEnd.setHours(23, 59, 59, 999);

  // --- 3. SEARCH AND DELETE ---
  // We search for the keyword "Checkout:" to target only our specific events
  const events = calendar.getEvents(searchStart, searchEnd, {search: 'Checkout:'});
  
  if (events.length === 0) {
    Logger.log('No checkout events found for this date range.');
    return;
  }

  // Confirm with the user before deleting everything
  // const response = Logger.log(
  //   'Confirm Deletion',
  //   `Found ${events.length} checkout events between ${searchStart.toLocaleDateString()} and ${searchEnd.toLocaleDateString()}. Do you want to delete them?`,
  //   SpreadsheetApp.getUi().ButtonSet.YES_NO
  // );

  // if (response !== SpreadsheetApp.getUi().Button.YES) {
  //   return;
  // }

  let deletedCount = 0;
  for (let i = 0; i < events.length; i++) {
    // Extra safety check: ensure the title actually starts with "Checkout:"
    if (events[i].getTitle().indexOf('Checkout:') === 0) {
      events[i].deleteEvent();
      deletedCount++;
    }
  }

  Logger.log(`Success! Deleted ${deletedCount} checkout events.`);
}